### ISSUE TITLE
modifying configuration parameters does not take effect

### ISSUE THREAD

**Issue by crashGG** [Awakened0/RetroArch-Minimal-Builds#1]
Hello, I forked your repo, but no matter how I modify the **./configure** parameters, for example, there is only one **--disable-ffmpeg** and finally git-act gets the same as your RetroArch-Win-x86_64-Minimal.7z The 6M size of the 7z  package. What am I doing wrong?

here is my workflow:
https://github.com/crashGG/RetroArch-Minimal-Builds/actions/runs/4431209119/workflow

here is git-action upload-release:
https://github.com/crashGG/RetroArch-Minimal-Builds/releases

**Comment by Awakened0** [comment]
That's because you haven't added installing QT or SDL into your msys2 environment as part of your modified script. So those haven't been included when compiling, making your build basically the same as my Minimal one. If you want QT and SDL you have to add them somewhere after the `install: >-` part of the script. Something like this might work:

```
        install: >-
          base-devel
          git
          wget
          make
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-ntldd
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-freetype
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-qt5
          mingw-w64-x86_64-openssl
          unzip
          p7zip
```

(openssl is listed as something to install for QT support according to the msys2 compilation guide: https://docs.libretro.com/development/retroarch/compilation/windows/)

If it still doesn't work, you might want to try adding any other missing packages under the "Environment configuration", "For 64-bit builds:" section of that guide.

**Comment by crashGG** [comment]
Thank you very much, the new build has met expectations.

**Comment by Awakened0** [comment]
Nice!
